#!/usr/bin/env node
/**
 * Boilerplate MCP Server generated by agent-builder.
 * Ensure you install @modelcontextprotocol/sdk.
 */
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

const server = new Server(
  {
    name: "agent-builder-generated-mcp",
    version: "1.0.0",
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// Define tools here based on your mcp-tool-schema.json
const myToolSchema = {
  name: "example_tool",
  description: "An example generated tool.",
  inputSchema: {
    type: "object",
    properties: {
      param1: { type: "string" }
    },
    required: ["param1"]
  }
};

server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [myToolSchema],
  };
});

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  if (request.params.name === "example_tool") {
    return {
      content: [
        {
          type: "text",
          text: `Executed example_tool with param1: ${request.params.arguments.param1}`,
        },
      ],
    };
  }
  throw new Error("Tool not found");
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("MCP Server is running on stdio");
}

main().catch(console.error);
